### ISSUE TITLE
Error when query sent during ingestion!

### ISSUE THREAD

**Issue by imanehaf** [Raphtory/Raphtory#148]
The experiment setup in on cluster mode with chronologically ordered dataset. This error pops up on one of the PMs when launching an LPA query before the ingestion is completed. Messages are only sent between neighbours in the view and I've only tested it on a rangeQuery() but I don't think it matters here. 

```
[Raphtory-akka.actor.default-dispatcher-73] ERROR akka.actor.OneForOneStrategy - key not found: 69236865
java.util.NoSuchElementException: key not found: 69236865
	at scala.collection.parallel.ParMapLike.default(ParMapLike.scala:40) ~[org.scala-lang.scala-library-2.12.4.jar:na]
	at scala.collection.parallel.ParMapLike.default$(ParMapLike.scala:40) ~[org.scala-lang.scala-library-2.12.4.jar:na]
	at scala.collection.parallel.mutable.ParTrieMap.default(ParTrieMap.scala:36) ~[org.scala-lang.scala-library-2.12.4.jar:na]
	at scala.collection.parallel.ParMapLike.apply(ParMapLike.scala:46) ~[org.scala-lang.scala-library-2.12.4.jar:na]
	at scala.collection.parallel.ParMapLike.apply$(ParMapLike.scala:44) ~[org.scala-lang.scala-library-2.12.4.jar:na]
	at scala.collection.parallel.mutable.ParTrieMap.apply(ParTrieMap.scala:36) ~[org.scala-lang.scala-library-2.12.4.jar:na]
	at com.raphtory.core.actors.PartitionManager.Workers.ReaderWorker.handleVertexMessage(ReaderWorker.scala:143) ~[com.raphtory.raphtory-latest.jar:latest]
	at com.raphtory.core.actors.PartitionManager.Workers.ReaderWorker$$anonfun$receive$1.applyOrElse(ReaderWorker.scala:50) ~[com.raphtory.raphtory-latest.jar:latest]
	at akka.actor.Actor.aroundReceive(Actor.scala:539) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
	at akka.actor.Actor.aroundReceive$(Actor.scala:537) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
	at com.raphtory.core.actors.PartitionManager.Workers.ReaderWorker.akka$actor$Timers$$super$aroundReceive(ReaderWorker.scala:22) ~[com.raphtory.raphtory-latest.jar:latest]
	at akka.actor.Timers.aroundReceive(Timers.scala:55) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
	at akka.actor.Timers.aroundReceive$(Timers.scala:40) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
	at com.raphtory.core.actors.PartitionManager.Workers.ReaderWorker.aroundReceive(ReaderWorker.scala:22) ~[com.raphtory.raphtory-latest.jar:latest]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
	at akka.actor.ActorCell.invoke(ActorCell.scala:581) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
	at akka.dispatch.Mailbox.run(Mailbox.scala:229) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[com.typesafe.akka.akka-actor_2.12-2.5.26.jar:2.5.26]
```

**Comment by miratepuffin** [comment]
I believe this is fixed with the new analysis model where the view of the graph has been built once at the start instead of adding new vertices/edges that arrive late.

**Comment by richardclegg** [comment]
I am on annual leave until 12th June and will not have a laptop with me.
